import matplotlib.pyplot as plt
from matplotlib.widgets import Button
from random import randrange

# A List of Tuples containing answers followed by solutions
# Basic problems 0-47
# Reciprocals 48-95
# Finding theta - Basic 96-120
# Finding theta - Reciprocals 121-143
# Basic with angles in degrees 144-192
problems = [
    (r'$sin(0)$', r'$0$'),
    (r'$sin\left(\frac{\pi}{6}\right)$', r'$\frac{1}{2}$'),
    (r'$sin\left(\frac{\pi}{4}\right)$', r'$\frac{\sqrt{2}}{2}$'),
    (r'$sin\left(\frac{\pi}{3}\right)$', r'$\frac{\sqrt{3}}{2}$'),
    (r'$sin\left(\frac{\pi}{2}\right)$', r'$1$'),
    (r'$sin\left(\frac{2\pi}{3}\right)$', r'$\frac{\sqrt{3}}{2}$'),
    (r'$sin\left(\frac{3\pi}{4}\right)$', r'$\frac{\sqrt{2}}{2}$'),
    (r'$sin\left(\frac{5\pi}{6}\right)$', r'$\frac{1}{2}$'),
    (r'$sin(\pi)$', r'$0$'),
    (r'$sin\left(\frac{7\pi}{6}\right)$', r'$-\frac{1}{2}$'),
    (r'$sin\left(\frac{5\pi}{4}\right)$', r'$-\frac{\sqrt{2}}{2}$'),
    (r'$sin\left(\frac{4\pi}{3}\right)$', r'$-\frac{\sqrt{3}}{2}$'),
    (r'$sin\left(\frac{3\pi}{2}\right)$', r'$-1$'),
    (r'$sin\left(\frac{5\pi}{3}\right)$', r'$-\frac{\sqrt{3}}{2}$'),
    (r'$sin\left(\frac{7\pi}{4}\right)$', r'$-\frac{\sqrt{2}}{2}$'),
    (r'$sin\left(\frac{11\pi}{6}\right)$', r'$-\frac{1}{2}$'),
    (r'$cos(0)$', r'$1$'),
    (r'$cos\left(\frac{\pi}{6}\right)$', r'$\frac{\sqrt{3}}{2}$'),
    (r'$cos\left(\frac{\pi}{4}\right)$', r'$\frac{\sqrt{2}}{2}$'),
    (r'$cos\left(\frac{\pi}{3}\right)$', r'$\frac{1}{2}$'),
    (r'$cos\left(\frac{\pi}{2}\right)$', r'$0$'),
    (r'$cos\left(\frac{2\pi}{3}\right)$', r'$-\frac{1}{2}$'),
    (r'$cos\left(\frac{3\pi}{4}\right)$', r'$-\frac{\sqrt{2}}{2}$'),
    (r'$cos\left(\frac{5\pi}{6}\right)$', r'$-\frac{\sqrt{3}}{2}$'),
    (r'$cos(\pi)$', r'$-1$'),
    (r'$cos\left(\frac{7\pi}{6}\right)$', r'$-\frac{\sqrt{3}}{2}$'),
    (r'$cos\left(\frac{5\pi}{4}\right)$', r'$-\frac{\sqrt{2}}{2}$'),
    (r'$cos\left(\frac{4\pi}{3}\right)$', r'$-\frac{1}{2}$'),
    (r'$cos\left(\frac{3\pi}{2}\right)$', r'$0$'),
    (r'$cos\left(\frac{5\pi}{3}\right)$', r'$\frac{1}{2}$'),
    (r'$cos\left(\frac{7\pi}{4}\right)$', r'$\frac{\sqrt{2}}{2}$'),
    (r'$cos\left(\frac{11\pi}{6}\right)$', r'$\frac{\sqrt{3}}{2}$'),
    (r'$tan(0)$', r'$0$'),
    (r'$tan\left(\frac{\pi}{6}\right)$', r'$\frac{\sqrt{3}}{3}$'),
    (r'$tan\left(\frac{\pi}{4}\right)$', r'$1$'),
    (r'$tan\left(\frac{\pi}{3}\right)$', r'$\sqrt{3}$'),
    (r'$tan\left(\frac{\pi}{2}\right)$', r'Undefined'),
    (r'$tan\left(\frac{2\pi}{3}\right)$', r'$-\sqrt{3}$'),
    (r'$tan\left(\frac{3\pi}{4}\right)$', r'$-1$'),
    (r'$tan\left(\frac{5\pi}{6}\right)$', r'$-\frac{\sqrt{3}}{3}$'),
    (r'$tan(\pi)$', r'$0$'),
    (r'$tan\left(\frac{7\pi}{6}\right)$', r'$\frac{\sqrt{3}}{3}$'),
    (r'$tan\left(\frac{5\pi}{4}\right)$', r'$1$'),
    (r'$tan\left(\frac{4\pi}{3}\right)$', r'$\sqrt{3}$'),
    (r'$tan\left(\frac{3\pi}{2}\right)$', r'Undefined'),
    (r'$tan\left(\frac{5\pi}{3}\right)$', r'$-\sqrt{3}$'),
    (r'$tan\left(\frac{7\pi}{4}\right)$', r'$-1$'),
    (r'$tan\left(\frac{11\pi}{6}\right)$', r'$-\frac{\sqrt{3}}{3}$'),
    (r'$csc(0)$', r'Undefined'),
    (r'$csc\left(\frac{\pi}{6}\right)$', r'$2$'),
    (r'$csc\left(\frac{\pi}{4}\right)$', r'$\sqrt{2}$'),
    (r'$csc\left(\frac{\pi}{3}\right)$', r'$\frac{2\sqrt{3}}{3}$'),
    (r'$csc\left(\frac{\pi}{2}\right)$', r'$1$'),
    (r'$csc\left(\frac{2\pi}{3}\right)$', r'$\frac{2\sqrt{3}}{3}$'),
    (r'$csc\left(\frac{3\pi}{4}\right)$', r'$\sqrt{2}$'),
    (r'$csc\left(\frac{5\pi}{6}\right)$', r'$2$'),
    (r'$csc(\pi)$', r'Undefined'),
    (r'$csc\left(\frac{7\pi}{6}\right)$', r'$-2$'),
    (r'$csc\left(\frac{5\pi}{4}\right)$', r'$-\sqrt{2}$'),
    (r'$csc\left(\frac{4\pi}{3}\right)$', r'$-\frac{2\sqrt{3}}{3}$'),
    (r'$csc\left(\frac{3\pi}{2}\right)$', r'$-1$'),
    (r'$csc\left(\frac{5\pi}{3}\right)$', r'$-\frac{2\sqrt{3}}{3}$'),
    (r'$csc\left(\frac{7\pi}{4}\right)$', r'$-\sqrt{2}$'),
    (r'$csc\left(\frac{11\pi}{6}\right)$', r'$-2$'),
    (r'$sec(0)$', r'$1$'),
    (r'$sec\left(\frac{\pi}{6}\right)$', r'$\frac{2\sqrt{3}}{3}$'),
    (r'$sec\left(\frac{\pi}{4}\right)$', r'$\sqrt{2}$'),
    (r'$sec\left(\frac{\pi}{3}\right)$', r'$2$'),
    (r'$sec\left(\frac{\pi}{2}\right)$', r'$Undefined$'),
    (r'$sec\left(\frac{2\pi}{3}\right)$', r'$-2$'),
    (r'$sec\left(\frac{3\pi}{4}\right)$', r'$-\sqrt{2}$'),
    (r'$sec\left(\frac{5\pi}{6}\right)$', r'$-\frac{2\sqrt{3}}{3}$'),
    (r'$sec(\pi)$', r'$-1$'),
    (r'$sec\left(\frac{7\pi}{6}\right)$', r'$-\frac{2\sqrt{3}}{3}$'),
    (r'$sec\left(\frac{5\pi}{4}\right)$', r'$-\sqrt{2}$'),
    (r'$sec\left(\frac{4\pi}{3}\right)$', r'$-2$'),
    (r'$sec\left(\frac{3\pi}{2}\right)$', r'$Undefined$'),
    (r'$sec\left(\frac{5\pi}{3}\right)$', r'$2$'),
    (r'$sec\left(\frac{7\pi}{4}\right)$', r'$\sqrt{2}$'),
    (r'$sec\left(\frac{11\pi}{6}\right)$', r'$\frac{2\sqrt{3}}{3}$'),
    (r'$cot(0)$', r'Undefined'),
    (r'$cot\left(\frac{\pi}{6}\right)$', r'$\sqrt{3}$'),
    (r'$cot\left(\frac{\pi}{4}\right)$', r'$1$'),
    (r'$cot\left(\frac{\pi}{3}\right)$', r'$\frac{\sqrt{3}}{3}$'),
    (r'$cot\left(\frac{\pi}{2}\right)$', r'$0$'),
    (r'$cot\left(\frac{2\pi}{3}\right)$', r'$-\frac{\sqrt{3}}{3}$'),
    (r'$cot\left(\frac{3\pi}{4}\right)$', r'$-1$'),
    (r'$cot\left(\frac{5\pi}{6}\right)$', r'$-\sqrt{3}$'),
    (r'$cot(\pi)$', r'Undefined'),
    (r'$cot\left(\frac{7\pi}{6}\right)$', r'$\sqrt{3}$'),
    (r'$cot\left(\frac{5\pi}{4}\right)$', r'$1$'),
    (r'$cot\left(\frac{4\pi}{3}\right)$', r'$\frac{\sqrt{3}}{3}$'),
    (r'$cot\left(\frac{3\pi}{2}\right)$', r'$0$'),
    (r'$cot\left(\frac{5\pi}{3}\right)$', r'$-\frac{\sqrt{3}}{3}$'),
    (r'$cot\left(\frac{7\pi}{4}\right)$', r'$-1$'),
    (r'$cot\left(\frac{11\pi}{6}\right)$', r'$-\sqrt{3}$'),
    (r'$sin(\theta)=0$', r'$\theta=0$'),
    (r'$sin(\theta)=\frac{1}{2}$', r'$\theta=\frac{\pi}{6}$'),
    (r'$sin(\theta)=\frac{\sqrt{2}}{2}$', r'$\theta=\frac{\pi}{4}$'),
    (r'$sin(\theta)=\frac{\sqrt{3}}{2}$', r'$\theta=\frac{\pi}{3}$'),
    (r'$sin(\theta)=1$', r'$\theta=\frac{\pi}{2}$'),
    (r'$sin(\theta)=-1$', r'$\theta=\frac{-\pi}{2}$'),
    (r'$sin(\theta)=-\frac{\sqrt{3}}{2}$', r'$\theta=\frac{-\pi}{3}$'),
    (r'$sin(\theta)=-\frac{\sqrt{2}}{2}$', r'$\theta=\frac{-\pi}{4}$'),
    (r'$sin(\theta)=-\frac{1}{2}$', r'$\theta=\frac{-\pi}{6}$'),
    (r'$cos(\theta)=1$', r'$\theta=0$'),
    (r'$cos(\theta)=\frac{\sqrt{3}}{2}$', r'$\theta=\frac{\pi}{6}$'),
    (r'$cos(\theta)=\frac{\sqrt{2}}{2}$', r'$\theta=\frac{\pi}{4}$'),
    (r'$cos(\theta)=\frac{1}{2}$', r'$\theta=\frac{\pi}{3}$'),
    (r'$cos(\theta)=0$', r'$\theta=\frac{\pi}{2}$'),
    (r'$cos(\theta)=-\frac{1}{2}$', r'$\theta=\frac{2\pi}{3}$'),
    (r'$cos(\theta)=-\frac{\sqrt{2}}{2}$', r'$\theta=\frac{3\pi}{4}$'),
    (r'$cos(\theta)=-\frac{\sqrt{3}}{2}$', r'$\theta=\frac{5\pi}{6}$'),
    (r'$cos(\theta)=-1$', r'$\theta=\pi$'),
    (r'$tan(\theta)=\frac{\sqrt{3}}{3}$', r'$\theta=\frac{\pi}{6}$'),
    (r'$tan(\theta)=1$', r'$\theta=\frac{\pi}{4}$'),
    (r'$tan(\theta)=\sqrt{3}$', r'$\theta=\frac{\pi}{3}$'),
    (r'$tan(\theta)=0$', r'$\theta=0$'),
    (r'$tan(\theta)=-\sqrt{3}$', r'$\theta=\frac{-\pi}{3}$'),
    (r'$tan(\theta)=-1$', r'$\theta=\frac{-\pi}{4}$'),
    (r'$tan(\theta)=-\frac{\sqrt{3}}{3}$', r'$\theta=\frac{-\pi}{6}$'),
    (r'$csc(\theta)=2$', r'$\theta=\frac{\pi}{6}$'),
    (r'$csc(\theta)=\sqrt{2}$', r'$\theta=\frac{\pi}{4}$'),
    (r'$csc(\theta)=\frac{2\sqrt{3}}{3}$', r'$\theta=\frac{\pi}{3}$'),
    (r'$csc(\theta)=1$', r'$\theta=\frac{\pi}{2}$'),
    (r'$csc(\theta)=-1$', r'$\theta=\frac{-\pi}{2}$'),
    (r'$csc(\theta)=-\frac{2\sqrt{3}}{3}$', r'$\theta=\frac{-\pi}{3}$'),
    (r'$csc(\theta)=-\sqrt{2}$', r'$\theta=\frac{-\pi}{4}$'),
    (r'$csc(\theta)=-2$', r'$\theta=\frac{-\pi}{6}$'),
    (r'$sec(\theta)=1$', r'$\theta=0$'),
    (r'$sec(\theta)=\frac{2\sqrt{3}}{3}$', r'$\theta=\frac{\pi}{6}$'),
    (r'$sec(\theta)=\sqrt{2}$', r'$\theta=\frac{\pi}{4}$'),
    (r'$sec(\theta)=2$', r'$\theta=\frac{\pi}{3}$'),
    (r'$sec(\theta)=-2$', r'$\theta=\frac{2\pi}{3}$'),
    (r'$sec(\theta)=-\sqrt{2}$', r'$\theta=\frac{3\pi}{4}$'),
    (r'$sec(\theta)=-\frac{2\sqrt{3}}{3}$', r'$\theta=\frac{5\pi}{6}$'),
    (r'$sec(\theta)=-1$', r'$\theta=\pi$'),
    (r'$cot(\theta)=\sqrt{3}$', r'$\theta=\frac{\pi}{6}$'),
    (r'$cot(\theta$', r'$\theta=\frac{\pi}{4})=1$'),
    (r'$cot(\theta)=\frac{\sqrt{3}}{3}$', r'$\theta=\frac{\pi}{3}$'),
    (r'$cot(\theta)=0$', r'$\theta=\frac{\pi}{2}$'),
    (r'$cot(\theta)=-\frac{\sqrt{3}}{3}$', r'$\theta=\frac{2\pi}{3}$'),
    (r'$cot(\theta)=-1$', r'$\theta=\frac{3\pi}{4}$'),
    (r'$cot(\theta)=-\sqrt{3}$', r'$\theta=\frac{5\pi}{6}$'),
    (r'$sin(0)$', r'$0$'),
    (r'$sin\left(30\right)$', r'$\frac{1}{2}$'),
    (r'$sin\left(45\right)$', r'$\frac{\sqrt{2}}{2}$'),
    (r'$sin\left(60\right)$', r'$\frac{\sqrt{3}}{2}$'),
    (r'$sin\left(90\right)$', r'$1$'),
    (r'$sin\left(120\right)$', r'$\frac{\sqrt{3}}{2}$'),
    (r'$sin\left(135\right)$', r'$\frac{\sqrt{2}}{2}$'),
    (r'$sin\left(150\right)$', r'$\frac{1}{2}$'),
    (r'$sin(180)$', r'$0$'),
    (r'$sin\left(210\right)$', r'$-\frac{1}{2}$'),
    (r'$sin\left(225\right)$', r'$-\frac{\sqrt{2}}{2}$'),
    (r'$sin\left(240\right)$', r'$-\frac{\sqrt{3}}{2}$'),
    (r'$sin\left(270\right)$', r'$-1$'),
    (r'$sin\left(300\right)$', r'$-\frac{\sqrt{3}}{2}$'),
    (r'$sin\left(315\right)$', r'$-\frac{\sqrt{2}}{2}$'),
    (r'$sin\left(330\right)$', r'$-\frac{1}{2}$'),
    (r'$cos(0)$', r'$1$'),
    (r'$cos\left(30\right)$', r'$\frac{\sqrt{3}}{2}$'),
    (r'$cos\left(45\right)$', r'$\frac{\sqrt{2}}{2}$'),
    (r'$cos\left(60\right)$', r'$\frac{1}{2}$'),
    (r'$cos\left(90\right)$', r'$0$'),
    (r'$cos\left(120\right)$', r'$-\frac{1}{2}$'),
    (r'$cos\left(135\right)$', r'$-\frac{\sqrt{2}}{2}$'),
    (r'$cos\left(150\right)$', r'$-\frac{\sqrt{3}}{2}$'),
    (r'$cos(180)$', r'$-1$'),
    (r'$cos\left(210\right)$', r'$-\frac{\sqrt{3}}{2}$'),
    (r'$cos\left(225\right)$', r'$-\frac{\sqrt{2}}{2}$'),
    (r'$cos\left(240\right)$', r'$-\frac{1}{2}$'),
    (r'$cos\left(270\right)$', r'$0$'),
    (r'$cos\left(300\right)$', r'$\frac{1}{2}$'),
    (r'$cos\left(315\right)$', r'$\frac{\sqrt{2}}{2}$'),
    (r'$cos\left(330\right)$', r'$\frac{\sqrt{3}}{2}$'),
    (r'$tan(0)$', r'$0$'),
    (r'$tan\left(30\right)$', r'$\frac{\sqrt{3}}{3}$'),
    (r'$tan\left(45\right)$', r'$1$'),
    (r'$tan\left(60\right)$', r'$\sqrt{3}$'),
    (r'$tan\left(90\right)$', r'Undefined'),
    (r'$tan\left(120\right)$', r'$-\sqrt{3}$'),
    (r'$tan\left(135\right)$', r'$-1$'),
    (r'$tan\left(150\right)$', r'$-\frac{\sqrt{3}}{3}$'),
    (r'$tan(180)$', r'$0$'),
    (r'$tan\left(210\right)$', r'$\frac{\sqrt{3}}{3}$'),
    (r'$tan\left(225\right)$', r'$1$'),
    (r'$tan\left(240\right)$', r'$\sqrt{3}$'),
    (r'$tan\left(270\right)$', r'Undefined'),
    (r'$tan\left(300\right)$', r'$-\sqrt{3}$'),
    (r'$tan\left(315\right)$', r'$-1$'),
    (r'$tan\left(330\right)$', r'$-\frac{\sqrt{3}}{3}$')
]

class Index(object):
    ind = -1
    problem_number = 0

    def next(self, event):
        self.ind += 1
        if self.ind%2 == 0:
            self.problem_number = randrange(144, 192)
            bnext.label.set_text(problems[self.problem_number][0])
        else:
            bnext.label.set_text(problems[self.problem_number][1])
        plt.draw()

click_handler = Index()
axnext = plt.axes([0.05, 0.05, .9, .9])
bnext = Button(axnext, "Start")
bnext.label.set_fontsize(64)
bnext.on_clicked(click_handler.next)

plt.draw()
plt.show()